/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecCommands;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecComponents;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecEvents;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecParent;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecProjects;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecStarterProjects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Structure of the devworkspace. This is also the specification of a devworkspace template.
 */
@ApiModel(description = "Structure of the devworkspace. This is also the specification of a devworkspace template.")

public class V1alpha2DevWorkspaceTemplateSpec {
  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Object attributes;

  public static final String SERIALIZED_NAME_COMMANDS = "commands";
  @SerializedName(SERIALIZED_NAME_COMMANDS)
  private List<V1alpha2DevWorkspaceTemplateSpecCommands> commands = null;

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  private List<V1alpha2DevWorkspaceTemplateSpecComponents> components = null;

  public static final String SERIALIZED_NAME_EVENTS = "events";
  @SerializedName(SERIALIZED_NAME_EVENTS)
  private V1alpha2DevWorkspaceTemplateSpecEvents events;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private V1alpha2DevWorkspaceTemplateSpecParent parent;

  public static final String SERIALIZED_NAME_PROJECTS = "projects";
  @SerializedName(SERIALIZED_NAME_PROJECTS)
  private List<V1alpha2DevWorkspaceTemplateSpecProjects> projects = null;

  public static final String SERIALIZED_NAME_STARTER_PROJECTS = "starterProjects";
  @SerializedName(SERIALIZED_NAME_STARTER_PROJECTS)
  private List<V1alpha2DevWorkspaceTemplateSpecStarterProjects> starterProjects = null;

  public static final String SERIALIZED_NAME_VARIABLES = "variables";
  @SerializedName(SERIALIZED_NAME_VARIABLES)
  private Map<String, String> variables = null;


  public V1alpha2DevWorkspaceTemplateSpec attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Map of implementation-dependant free-form YAML attributes.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of implementation-dependant free-form YAML attributes.")

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public V1alpha2DevWorkspaceTemplateSpec commands(List<V1alpha2DevWorkspaceTemplateSpecCommands> commands) {
    
    this.commands = commands;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpec addCommandsItem(V1alpha2DevWorkspaceTemplateSpecCommands commandsItem) {
    if (this.commands == null) {
      this.commands = new ArrayList<>();
    }
    this.commands.add(commandsItem);
    return this;
  }

   /**
   * Predefined, ready-to-use, devworkspace-related commands
   * @return commands
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Predefined, ready-to-use, devworkspace-related commands")

  public List<V1alpha2DevWorkspaceTemplateSpecCommands> getCommands() {
    return commands;
  }


  public void setCommands(List<V1alpha2DevWorkspaceTemplateSpecCommands> commands) {
    this.commands = commands;
  }


  public V1alpha2DevWorkspaceTemplateSpec components(List<V1alpha2DevWorkspaceTemplateSpecComponents> components) {
    
    this.components = components;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpec addComponentsItem(V1alpha2DevWorkspaceTemplateSpecComponents componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

   /**
   * List of the devworkspace components, such as editor and plugins, user-provided containers, or other types of components
   * @return components
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of the devworkspace components, such as editor and plugins, user-provided containers, or other types of components")

  public List<V1alpha2DevWorkspaceTemplateSpecComponents> getComponents() {
    return components;
  }


  public void setComponents(List<V1alpha2DevWorkspaceTemplateSpecComponents> components) {
    this.components = components;
  }


  public V1alpha2DevWorkspaceTemplateSpec events(V1alpha2DevWorkspaceTemplateSpecEvents events) {
    
    this.events = events;
    return this;
  }

   /**
   * Get events
   * @return events
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecEvents getEvents() {
    return events;
  }


  public void setEvents(V1alpha2DevWorkspaceTemplateSpecEvents events) {
    this.events = events;
  }


  public V1alpha2DevWorkspaceTemplateSpec parent(V1alpha2DevWorkspaceTemplateSpecParent parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecParent getParent() {
    return parent;
  }


  public void setParent(V1alpha2DevWorkspaceTemplateSpecParent parent) {
    this.parent = parent;
  }


  public V1alpha2DevWorkspaceTemplateSpec projects(List<V1alpha2DevWorkspaceTemplateSpecProjects> projects) {
    
    this.projects = projects;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpec addProjectsItem(V1alpha2DevWorkspaceTemplateSpecProjects projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<>();
    }
    this.projects.add(projectsItem);
    return this;
  }

   /**
   * Projects worked on in the devworkspace, containing names and sources locations
   * @return projects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Projects worked on in the devworkspace, containing names and sources locations")

  public List<V1alpha2DevWorkspaceTemplateSpecProjects> getProjects() {
    return projects;
  }


  public void setProjects(List<V1alpha2DevWorkspaceTemplateSpecProjects> projects) {
    this.projects = projects;
  }


  public V1alpha2DevWorkspaceTemplateSpec starterProjects(List<V1alpha2DevWorkspaceTemplateSpecStarterProjects> starterProjects) {
    
    this.starterProjects = starterProjects;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpec addStarterProjectsItem(V1alpha2DevWorkspaceTemplateSpecStarterProjects starterProjectsItem) {
    if (this.starterProjects == null) {
      this.starterProjects = new ArrayList<>();
    }
    this.starterProjects.add(starterProjectsItem);
    return this;
  }

   /**
   * StarterProjects is a project that can be used as a starting point when bootstrapping new projects
   * @return starterProjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "StarterProjects is a project that can be used as a starting point when bootstrapping new projects")

  public List<V1alpha2DevWorkspaceTemplateSpecStarterProjects> getStarterProjects() {
    return starterProjects;
  }


  public void setStarterProjects(List<V1alpha2DevWorkspaceTemplateSpecStarterProjects> starterProjects) {
    this.starterProjects = starterProjects;
  }


  public V1alpha2DevWorkspaceTemplateSpec variables(Map<String, String> variables) {
    
    this.variables = variables;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpec putVariablesItem(String key, String variablesItem) {
    if (this.variables == null) {
      this.variables = new HashMap<>();
    }
    this.variables.put(key, variablesItem);
    return this;
  }

   /**
   * Map of key-value variables used for string replacement in the devfile. Values can be referenced via {{variable-key}} to replace the corresponding value in string fields in the devfile. Replacement cannot be used for   - schemaVersion, metadata, parent source   - element identifiers, e.g. command id, component name, endpoint name, project name   - references to identifiers, e.g. in events, a command&#39;s component, container&#39;s volume mount name   - string enums, e.g. command group kind, endpoint exposure
   * @return variables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of key-value variables used for string replacement in the devfile. Values can be referenced via {{variable-key}} to replace the corresponding value in string fields in the devfile. Replacement cannot be used for   - schemaVersion, metadata, parent source   - element identifiers, e.g. command id, component name, endpoint name, project name   - references to identifiers, e.g. in events, a command's component, container's volume mount name   - string enums, e.g. command group kind, endpoint exposure")

  public Map<String, String> getVariables() {
    return variables;
  }


  public void setVariables(Map<String, String> variables) {
    this.variables = variables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2DevWorkspaceTemplateSpec v1alpha2DevWorkspaceTemplateSpec = (V1alpha2DevWorkspaceTemplateSpec) o;
    return Objects.equals(this.attributes, v1alpha2DevWorkspaceTemplateSpec.attributes) &&
        Objects.equals(this.commands, v1alpha2DevWorkspaceTemplateSpec.commands) &&
        Objects.equals(this.components, v1alpha2DevWorkspaceTemplateSpec.components) &&
        Objects.equals(this.events, v1alpha2DevWorkspaceTemplateSpec.events) &&
        Objects.equals(this.parent, v1alpha2DevWorkspaceTemplateSpec.parent) &&
        Objects.equals(this.projects, v1alpha2DevWorkspaceTemplateSpec.projects) &&
        Objects.equals(this.starterProjects, v1alpha2DevWorkspaceTemplateSpec.starterProjects) &&
        Objects.equals(this.variables, v1alpha2DevWorkspaceTemplateSpec.variables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, commands, components, events, parent, projects, starterProjects, variables);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2DevWorkspaceTemplateSpec {\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    starterProjects: ").append(toIndentedString(starterProjects)).append("\n");
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

