/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImageDockerfile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Allows specifying the definition of an image for outer loop builds
 */
@ApiModel(description = "Allows specifying the definition of an image for outer loop builds")

public class V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage {
  public static final String SERIALIZED_NAME_AUTO_BUILD = "autoBuild";
  @SerializedName(SERIALIZED_NAME_AUTO_BUILD)
  private Boolean autoBuild;

  public static final String SERIALIZED_NAME_DOCKERFILE = "dockerfile";
  @SerializedName(SERIALIZED_NAME_DOCKERFILE)
  private V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImageDockerfile dockerfile;

  public static final String SERIALIZED_NAME_IMAGE_NAME = "imageName";
  @SerializedName(SERIALIZED_NAME_IMAGE_NAME)
  private String imageName;


  public V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage autoBuild(Boolean autoBuild) {
    
    this.autoBuild = autoBuild;
    return this;
  }

   /**
   * Defines if the image should be built during startup.  Default value is &#x60;false&#x60;
   * @return autoBuild
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Defines if the image should be built during startup.  Default value is `false`")

  public Boolean getAutoBuild() {
    return autoBuild;
  }


  public void setAutoBuild(Boolean autoBuild) {
    this.autoBuild = autoBuild;
  }


  public V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage dockerfile(V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImageDockerfile dockerfile) {
    
    this.dockerfile = dockerfile;
    return this;
  }

   /**
   * Get dockerfile
   * @return dockerfile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImageDockerfile getDockerfile() {
    return dockerfile;
  }


  public void setDockerfile(V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImageDockerfile dockerfile) {
    this.dockerfile = dockerfile;
  }


  public V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage imageName(String imageName) {
    
    this.imageName = imageName;
    return this;
  }

   /**
   * Name of the image for the resulting outerloop build
   * @return imageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the image for the resulting outerloop build")

  public String getImageName() {
    return imageName;
  }


  public void setImageName(String imageName) {
    this.imageName = imageName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage v1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage = (V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage) o;
    return Objects.equals(this.autoBuild, v1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage.autoBuild) &&
        Objects.equals(this.dockerfile, v1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage.dockerfile) &&
        Objects.equals(this.imageName, v1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage.imageName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoBuild, dockerfile, imageName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2DevWorkspaceTemplateSpecParentComponentsItemsPluginComponentsItemsImage {\n");
    sb.append("    autoBuild: ").append(toIndentedString(autoBuild)).append("\n");
    sb.append("    dockerfile: ").append(toIndentedString(dockerfile)).append("\n");
    sb.append("    imageName: ").append(toIndentedString(imageName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

