/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceSpecTemplate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DevWorkspaceSpec defines the desired state of DevWorkspace
 */
@ApiModel(description = "DevWorkspaceSpec defines the desired state of DevWorkspace")

public class V1alpha2DevWorkspaceSpec {
  public static final String SERIALIZED_NAME_ROUTING_CLASS = "routingClass";
  @SerializedName(SERIALIZED_NAME_ROUTING_CLASS)
  private String routingClass;

  public static final String SERIALIZED_NAME_STARTED = "started";
  @SerializedName(SERIALIZED_NAME_STARTED)
  private Boolean started;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  private V1alpha2DevWorkspaceSpecTemplate template;


  public V1alpha2DevWorkspaceSpec routingClass(String routingClass) {
    
    this.routingClass = routingClass;
    return this;
  }

   /**
   * Get routingClass
   * @return routingClass
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoutingClass() {
    return routingClass;
  }


  public void setRoutingClass(String routingClass) {
    this.routingClass = routingClass;
  }


  public V1alpha2DevWorkspaceSpec started(Boolean started) {
    
    this.started = started;
    return this;
  }

   /**
   * Get started
   * @return started
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getStarted() {
    return started;
  }


  public void setStarted(Boolean started) {
    this.started = started;
  }


  public V1alpha2DevWorkspaceSpec template(V1alpha2DevWorkspaceSpecTemplate template) {
    
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceSpecTemplate getTemplate() {
    return template;
  }


  public void setTemplate(V1alpha2DevWorkspaceSpecTemplate template) {
    this.template = template;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2DevWorkspaceSpec v1alpha2DevWorkspaceSpec = (V1alpha2DevWorkspaceSpec) o;
    return Objects.equals(this.routingClass, v1alpha2DevWorkspaceSpec.routingClass) &&
        Objects.equals(this.started, v1alpha2DevWorkspaceSpec.started) &&
        Objects.equals(this.template, v1alpha2DevWorkspaceSpec.template);
  }

  @Override
  public int hashCode() {
    return Objects.hash(routingClass, started, template);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2DevWorkspaceSpec {\n");
    sb.append("    routingClass: ").append(toIndentedString(routingClass)).append("\n");
    sb.append("    started: ").append(toIndentedString(started)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

