/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginCommands;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginComponents;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginKubernetes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Allows importing a plugin.  Plugins are mainly imported devfiles that contribute components, commands and events as a consistent single unit. They are defined in either YAML files following the devfile syntax, or as &#x60;DevWorkspaceTemplate&#x60; Kubernetes Custom Resources
 */
@ApiModel(description = "Allows importing a plugin.  Plugins are mainly imported devfiles that contribute components, commands and events as a consistent single unit. They are defined in either YAML files following the devfile syntax, or as `DevWorkspaceTemplate` Kubernetes Custom Resources")

public class V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin {
  public static final String SERIALIZED_NAME_COMMANDS = "commands";
  @SerializedName(SERIALIZED_NAME_COMMANDS)
  private List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginCommands> commands = null;

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  private List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginComponents> components = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_KUBERNETES = "kubernetes";
  @SerializedName(SERIALIZED_NAME_KUBERNETES)
  private V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginKubernetes kubernetes;

  public static final String SERIALIZED_NAME_REGISTRY_URL = "registryUrl";
  @SerializedName(SERIALIZED_NAME_REGISTRY_URL)
  private String registryUrl;

  public static final String SERIALIZED_NAME_URI = "uri";
  @SerializedName(SERIALIZED_NAME_URI)
  private String uri;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin commands(List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginCommands> commands) {
    
    this.commands = commands;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin addCommandsItem(V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginCommands commandsItem) {
    if (this.commands == null) {
      this.commands = new ArrayList<>();
    }
    this.commands.add(commandsItem);
    return this;
  }

   /**
   * Overrides of commands encapsulated in a parent devfile or a plugin. Overriding is done according to K8S strategic merge patch standard rules.
   * @return commands
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Overrides of commands encapsulated in a parent devfile or a plugin. Overriding is done according to K8S strategic merge patch standard rules.")

  public List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginCommands> getCommands() {
    return commands;
  }


  public void setCommands(List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginCommands> commands) {
    this.commands = commands;
  }


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin components(List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginComponents> components) {
    
    this.components = components;
    return this;
  }

  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin addComponentsItem(V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginComponents componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

   /**
   * Overrides of components encapsulated in a parent devfile or a plugin. Overriding is done according to K8S strategic merge patch standard rules.
   * @return components
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Overrides of components encapsulated in a parent devfile or a plugin. Overriding is done according to K8S strategic merge patch standard rules.")

  public List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginComponents> getComponents() {
    return components;
  }


  public void setComponents(List<V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginComponents> components) {
    this.components = components;
  }


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Id in a registry that contains a Devfile yaml file
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id in a registry that contains a Devfile yaml file")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin kubernetes(V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginKubernetes kubernetes) {
    
    this.kubernetes = kubernetes;
    return this;
  }

   /**
   * Get kubernetes
   * @return kubernetes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginKubernetes getKubernetes() {
    return kubernetes;
  }


  public void setKubernetes(V1alpha2DevWorkspaceTemplateSpecComponentsItemsPluginKubernetes kubernetes) {
    this.kubernetes = kubernetes;
  }


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin registryUrl(String registryUrl) {
    
    this.registryUrl = registryUrl;
    return this;
  }

   /**
   * Registry URL to pull the parent devfile from when using id in the parent reference. To ensure the parent devfile gets resolved consistently in different environments, it is recommended to always specify the &#x60;registryUrl&#x60; when &#x60;id&#x60; is used.
   * @return registryUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Registry URL to pull the parent devfile from when using id in the parent reference. To ensure the parent devfile gets resolved consistently in different environments, it is recommended to always specify the `registryUrl` when `id` is used.")

  public String getRegistryUrl() {
    return registryUrl;
  }


  public void setRegistryUrl(String registryUrl) {
    this.registryUrl = registryUrl;
  }


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin uri(String uri) {
    
    this.uri = uri;
    return this;
  }

   /**
   * URI Reference of a parent devfile YAML file. It can be a full URL or a relative URI with the current devfile as the base URI.
   * @return uri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URI Reference of a parent devfile YAML file. It can be a full URL or a relative URI with the current devfile as the base URI.")

  public String getUri() {
    return uri;
  }


  public void setUri(String uri) {
    this.uri = uri;
  }


  public V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Specific stack/sample version to pull the parent devfile from, when using id in the parent reference. To specify &#x60;version&#x60;, &#x60;id&#x60; must be defined and used as the import reference source. &#x60;version&#x60; can be either a specific stack version, or &#x60;latest&#x60;. If no &#x60;version&#x60; specified, default version will be used.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Specific stack/sample version to pull the parent devfile from, when using id in the parent reference. To specify `version`, `id` must be defined and used as the import reference source. `version` can be either a specific stack version, or `latest`. If no `version` specified, default version will be used.")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin = (V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin) o;
    return Objects.equals(this.commands, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.commands) &&
        Objects.equals(this.components, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.components) &&
        Objects.equals(this.id, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.id) &&
        Objects.equals(this.kubernetes, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.kubernetes) &&
        Objects.equals(this.registryUrl, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.registryUrl) &&
        Objects.equals(this.uri, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.uri) &&
        Objects.equals(this.version, v1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commands, components, id, kubernetes, registryUrl, uri, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2DevWorkspaceTemplateSpecComponentsItemsPlugin {\n");
    sb.append("    commands: ").append(toIndentedString(commands)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kubernetes: ").append(toIndentedString(kubernetes)).append("\n");
    sb.append("    registryUrl: ").append(toIndentedString(registryUrl)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

