/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DevWorkspaceStatus defines the observed state of DevWorkspace
 */
@ApiModel(description = "DevWorkspaceStatus defines the observed state of DevWorkspace")

public class V1alpha2DevWorkspaceStatus {
  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1alpha2DevWorkspaceStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_DEVWORKSPACE_ID = "devworkspaceId";
  @SerializedName(SERIALIZED_NAME_DEVWORKSPACE_ID)
  private String devworkspaceId;

  public static final String SERIALIZED_NAME_MAIN_URL = "mainUrl";
  @SerializedName(SERIALIZED_NAME_MAIN_URL)
  private String mainUrl;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PHASE = "phase";
  @SerializedName(SERIALIZED_NAME_PHASE)
  private String phase;


  public V1alpha2DevWorkspaceStatus conditions(List<V1alpha2DevWorkspaceStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1alpha2DevWorkspaceStatus addConditionsItem(V1alpha2DevWorkspaceStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions represent the latest available observations of an object&#39;s state
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Conditions represent the latest available observations of an object's state")

  public List<V1alpha2DevWorkspaceStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1alpha2DevWorkspaceStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1alpha2DevWorkspaceStatus devworkspaceId(String devworkspaceId) {
    
    this.devworkspaceId = devworkspaceId;
    return this;
  }

   /**
   * Id of the DevWorkspace
   * @return devworkspaceId
  **/
  @ApiModelProperty(required = true, value = "Id of the DevWorkspace")

  public String getDevworkspaceId() {
    return devworkspaceId;
  }


  public void setDevworkspaceId(String devworkspaceId) {
    this.devworkspaceId = devworkspaceId;
  }


  public V1alpha2DevWorkspaceStatus mainUrl(String mainUrl) {
    
    this.mainUrl = mainUrl;
    return this;
  }

   /**
   * Main URL for this DevWorkspace
   * @return mainUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Main URL for this DevWorkspace")

  public String getMainUrl() {
    return mainUrl;
  }


  public void setMainUrl(String mainUrl) {
    this.mainUrl = mainUrl;
  }


  public V1alpha2DevWorkspaceStatus message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Message is a short user-readable message giving additional information about an object&#39;s state
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Message is a short user-readable message giving additional information about an object's state")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public V1alpha2DevWorkspaceStatus phase(String phase) {
    
    this.phase = phase;
    return this;
  }

   /**
   * Get phase
   * @return phase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPhase() {
    return phase;
  }


  public void setPhase(String phase) {
    this.phase = phase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2DevWorkspaceStatus v1alpha2DevWorkspaceStatus = (V1alpha2DevWorkspaceStatus) o;
    return Objects.equals(this.conditions, v1alpha2DevWorkspaceStatus.conditions) &&
        Objects.equals(this.devworkspaceId, v1alpha2DevWorkspaceStatus.devworkspaceId) &&
        Objects.equals(this.mainUrl, v1alpha2DevWorkspaceStatus.mainUrl) &&
        Objects.equals(this.message, v1alpha2DevWorkspaceStatus.message) &&
        Objects.equals(this.phase, v1alpha2DevWorkspaceStatus.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, devworkspaceId, mainUrl, message, phase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2DevWorkspaceStatus {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    devworkspaceId: ").append(toIndentedString(devworkspaceId)).append("\n");
    sb.append("    mainUrl: ").append(toIndentedString(mainUrl)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

