/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsApply;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsComposite;
import io.github.che_incubator.devfile.kubernetes.client.models.V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsExec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha2DevWorkspaceTemplateSpecParentCommands
 */

public class V1alpha2DevWorkspaceTemplateSpecParentCommands {
  public static final String SERIALIZED_NAME_APPLY = "apply";
  @SerializedName(SERIALIZED_NAME_APPLY)
  private V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsApply apply;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Object attributes;

  public static final String SERIALIZED_NAME_COMPOSITE = "composite";
  @SerializedName(SERIALIZED_NAME_COMPOSITE)
  private V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsComposite composite;

  public static final String SERIALIZED_NAME_EXEC = "exec";
  @SerializedName(SERIALIZED_NAME_EXEC)
  private V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsExec exec;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;


  public V1alpha2DevWorkspaceTemplateSpecParentCommands apply(V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsApply apply) {
    
    this.apply = apply;
    return this;
  }

   /**
   * Get apply
   * @return apply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsApply getApply() {
    return apply;
  }


  public void setApply(V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsApply apply) {
    this.apply = apply;
  }


  public V1alpha2DevWorkspaceTemplateSpecParentCommands attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Map of implementation-dependant free-form YAML attributes.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of implementation-dependant free-form YAML attributes.")

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public V1alpha2DevWorkspaceTemplateSpecParentCommands composite(V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsComposite composite) {
    
    this.composite = composite;
    return this;
  }

   /**
   * Get composite
   * @return composite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsComposite getComposite() {
    return composite;
  }


  public void setComposite(V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsComposite composite) {
    this.composite = composite;
  }


  public V1alpha2DevWorkspaceTemplateSpecParentCommands exec(V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsExec exec) {
    
    this.exec = exec;
    return this;
  }

   /**
   * Get exec
   * @return exec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsExec getExec() {
    return exec;
  }


  public void setExec(V1alpha2DevWorkspaceTemplateSpecParentCommandsItemsExec exec) {
    this.exec = exec;
  }


  public V1alpha2DevWorkspaceTemplateSpecParentCommands id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Mandatory identifier that allows referencing this command in composite commands, from a parent, or in events.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Mandatory identifier that allows referencing this command in composite commands, from a parent, or in events.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2DevWorkspaceTemplateSpecParentCommands v1alpha2DevWorkspaceTemplateSpecParentCommands = (V1alpha2DevWorkspaceTemplateSpecParentCommands) o;
    return Objects.equals(this.apply, v1alpha2DevWorkspaceTemplateSpecParentCommands.apply) &&
        Objects.equals(this.attributes, v1alpha2DevWorkspaceTemplateSpecParentCommands.attributes) &&
        Objects.equals(this.composite, v1alpha2DevWorkspaceTemplateSpecParentCommands.composite) &&
        Objects.equals(this.exec, v1alpha2DevWorkspaceTemplateSpecParentCommands.exec) &&
        Objects.equals(this.id, v1alpha2DevWorkspaceTemplateSpecParentCommands.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apply, attributes, composite, exec, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2DevWorkspaceTemplateSpecParentCommands {\n");
    sb.append("    apply: ").append(toIndentedString(apply)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    composite: ").append(toIndentedString(composite)).append("\n");
    sb.append("    exec: ").append(toIndentedString(exec)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

