/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Bindings of commands to events. Each command is referred-to by its name.
 */
@ApiModel(description = "Bindings of commands to events. Each command is referred-to by its name.")

public class V220DevfileEvents {
  public static final String SERIALIZED_NAME_POST_START = "postStart";
  @SerializedName(SERIALIZED_NAME_POST_START)
  private List<String> postStart = null;

  public static final String SERIALIZED_NAME_POST_STOP = "postStop";
  @SerializedName(SERIALIZED_NAME_POST_STOP)
  private List<String> postStop = null;

  public static final String SERIALIZED_NAME_PRE_START = "preStart";
  @SerializedName(SERIALIZED_NAME_PRE_START)
  private List<String> preStart = null;

  public static final String SERIALIZED_NAME_PRE_STOP = "preStop";
  @SerializedName(SERIALIZED_NAME_PRE_STOP)
  private List<String> preStop = null;


  public V220DevfileEvents postStart(List<String> postStart) {
    
    this.postStart = postStart;
    return this;
  }

  public V220DevfileEvents addPostStartItem(String postStartItem) {
    if (this.postStart == null) {
      this.postStart = new ArrayList<>();
    }
    this.postStart.add(postStartItem);
    return this;
  }

   /**
   * IDs of commands that should be executed after the devworkspace is completely started. In the case of Che-Theia, these commands should be executed after all plugins and extensions have started, including project cloning. This means that those commands are not triggered until the user opens the IDE in his browser.
   * @return postStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs of commands that should be executed after the devworkspace is completely started. In the case of Che-Theia, these commands should be executed after all plugins and extensions have started, including project cloning. This means that those commands are not triggered until the user opens the IDE in his browser.")

  public List<String> getPostStart() {
    return postStart;
  }


  public void setPostStart(List<String> postStart) {
    this.postStart = postStart;
  }


  public V220DevfileEvents postStop(List<String> postStop) {
    
    this.postStop = postStop;
    return this;
  }

  public V220DevfileEvents addPostStopItem(String postStopItem) {
    if (this.postStop == null) {
      this.postStop = new ArrayList<>();
    }
    this.postStop.add(postStopItem);
    return this;
  }

   /**
   * IDs of commands that should be executed after stopping the devworkspace.
   * @return postStop
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs of commands that should be executed after stopping the devworkspace.")

  public List<String> getPostStop() {
    return postStop;
  }


  public void setPostStop(List<String> postStop) {
    this.postStop = postStop;
  }


  public V220DevfileEvents preStart(List<String> preStart) {
    
    this.preStart = preStart;
    return this;
  }

  public V220DevfileEvents addPreStartItem(String preStartItem) {
    if (this.preStart == null) {
      this.preStart = new ArrayList<>();
    }
    this.preStart.add(preStartItem);
    return this;
  }

   /**
   * IDs of commands that should be executed before the devworkspace start. Kubernetes-wise, these commands would typically be executed in init containers of the devworkspace POD.
   * @return preStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs of commands that should be executed before the devworkspace start. Kubernetes-wise, these commands would typically be executed in init containers of the devworkspace POD.")

  public List<String> getPreStart() {
    return preStart;
  }


  public void setPreStart(List<String> preStart) {
    this.preStart = preStart;
  }


  public V220DevfileEvents preStop(List<String> preStop) {
    
    this.preStop = preStop;
    return this;
  }

  public V220DevfileEvents addPreStopItem(String preStopItem) {
    if (this.preStop == null) {
      this.preStop = new ArrayList<>();
    }
    this.preStop.add(preStopItem);
    return this;
  }

   /**
   * IDs of commands that should be executed before stopping the devworkspace.
   * @return preStop
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IDs of commands that should be executed before stopping the devworkspace.")

  public List<String> getPreStop() {
    return preStop;
  }


  public void setPreStop(List<String> preStop) {
    this.preStop = preStop;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V220DevfileEvents v220DevfileEvents = (V220DevfileEvents) o;
    return Objects.equals(this.postStart, v220DevfileEvents.postStart) &&
        Objects.equals(this.postStop, v220DevfileEvents.postStop) &&
        Objects.equals(this.preStart, v220DevfileEvents.preStart) &&
        Objects.equals(this.preStop, v220DevfileEvents.preStop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postStart, postStop, preStart, preStop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V220DevfileEvents {\n");
    sb.append("    postStart: ").append(toIndentedString(postStart)).append("\n");
    sb.append("    postStop: ").append(toIndentedString(postStop)).append("\n");
    sb.append("    preStart: ").append(toIndentedString(preStart)).append("\n");
    sb.append("    preStop: ").append(toIndentedString(preStop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

