/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.che_incubator.devfile.kubernetes.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.che_incubator.devfile.kubernetes.client.models.V220DevfileParentCommandsItemsApply;
import io.github.che_incubator.devfile.kubernetes.client.models.V220DevfileParentCommandsItemsComposite;
import io.github.che_incubator.devfile.kubernetes.client.models.V220DevfileParentCommandsItemsExec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V220DevfileParentCommands
 */

public class V220DevfileParentCommands {
  public static final String SERIALIZED_NAME_APPLY = "apply";
  @SerializedName(SERIALIZED_NAME_APPLY)
  private V220DevfileParentCommandsItemsApply apply;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Object attributes;

  public static final String SERIALIZED_NAME_COMPOSITE = "composite";
  @SerializedName(SERIALIZED_NAME_COMPOSITE)
  private V220DevfileParentCommandsItemsComposite composite;

  public static final String SERIALIZED_NAME_EXEC = "exec";
  @SerializedName(SERIALIZED_NAME_EXEC)
  private V220DevfileParentCommandsItemsExec exec;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;


  public V220DevfileParentCommands apply(V220DevfileParentCommandsItemsApply apply) {
    
    this.apply = apply;
    return this;
  }

   /**
   * Get apply
   * @return apply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V220DevfileParentCommandsItemsApply getApply() {
    return apply;
  }


  public void setApply(V220DevfileParentCommandsItemsApply apply) {
    this.apply = apply;
  }


  public V220DevfileParentCommands attributes(Object attributes) {
    
    this.attributes = attributes;
    return this;
  }

   /**
   * Map of implementation-dependant free-form YAML attributes.
   * @return attributes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of implementation-dependant free-form YAML attributes.")

  public Object getAttributes() {
    return attributes;
  }


  public void setAttributes(Object attributes) {
    this.attributes = attributes;
  }


  public V220DevfileParentCommands composite(V220DevfileParentCommandsItemsComposite composite) {
    
    this.composite = composite;
    return this;
  }

   /**
   * Get composite
   * @return composite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V220DevfileParentCommandsItemsComposite getComposite() {
    return composite;
  }


  public void setComposite(V220DevfileParentCommandsItemsComposite composite) {
    this.composite = composite;
  }


  public V220DevfileParentCommands exec(V220DevfileParentCommandsItemsExec exec) {
    
    this.exec = exec;
    return this;
  }

   /**
   * Get exec
   * @return exec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V220DevfileParentCommandsItemsExec getExec() {
    return exec;
  }


  public void setExec(V220DevfileParentCommandsItemsExec exec) {
    this.exec = exec;
  }


  public V220DevfileParentCommands id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Mandatory identifier that allows referencing this command in composite commands, from a parent, or in events.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Mandatory identifier that allows referencing this command in composite commands, from a parent, or in events.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V220DevfileParentCommands v220DevfileParentCommands = (V220DevfileParentCommands) o;
    return Objects.equals(this.apply, v220DevfileParentCommands.apply) &&
        Objects.equals(this.attributes, v220DevfileParentCommands.attributes) &&
        Objects.equals(this.composite, v220DevfileParentCommands.composite) &&
        Objects.equals(this.exec, v220DevfileParentCommands.exec) &&
        Objects.equals(this.id, v220DevfileParentCommands.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apply, attributes, composite, exec, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V220DevfileParentCommands {\n");
    sb.append("    apply: ").append(toIndentedString(apply)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    composite: ").append(toIndentedString(composite)).append("\n");
    sb.append("    exec: ").append(toIndentedString(exec)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

